spring:
  application:
    name: assurance
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/tinubu?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:tinubu}
    password: ${SPRING_DATASOURCE_PASSWORD:tinubu}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate', 'update', 'create', or 'create-drop' as appropriate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080  # Optional: change server port if needed
